### ISSUE TITLE
TypeError: 'type' object is not subscriptable   - while running on a docker container

### ISSUE THREAD

**Issue by sreejith-mohanan** [PeterYusuke/dialogflow-log-parser#10]
I am trying to user this library inside a docker container, As soon as i am importing, it throws an error

from dialogflow_log_parser.es import response_to_dict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/dialogflow_log_parser/__init__.py", line 1, in <module>
    from . import es
  File "/usr/local/lib/python3.7/site-packages/dialogflow_log_parser/es/__init__.py", line 1, in <module>
    from . import parser
  File "/usr/local/lib/python3.7/site-packages/dialogflow_log_parser/es/parser.py", line 2, in <module>
    from .logic import response_conf_logic, response_hocon_logic
  File "/usr/local/lib/python3.7/site-packages/dialogflow_log_parser/es/logic/__init__.py", line 1, in <module>
    from .conf_logic import ResponseConfLogic
  File "/usr/local/lib/python3.7/site-packages/dialogflow_log_parser/es/logic/conf_logic.py", line 5, in <module>
    class BaseConfLogic():
  File "/usr/local/lib/python3.7/site-packages/dialogflow_log_parser/es/logic/conf_logic.py", line 9, in BaseConfLogic
    def get_indeices_of_regex(self, config_list: list[str], regex: str):
TypeError: 'type' object is not subscriptable

**Comment by sreejith-mohanan** [comment]
I think this error was because of "type hinting generics", which was introduced in python 3.8 only and i was using python 3.7 on that docker container.
